spring:
  application:
    max-metadata-size: ${MAX_METADATA_SIZE:16384}
    name: ${DRPC_APP_NAME:dshackle}
  zipkin:
    enabled: ${ENABLE_COLLECT_SPANS:false}
    base-url: ${ZIPKIN_URL:https://trace.drpc.dev/}
  sleuth:
    span-filter:
      additional-span-name-patterns-to-ignore:
        - "^grpcChannelExecutor$"
        - ".+NativeSubscribe"
        - ".+SubscribeHead"
        - ".+SubscribeBalance"
        - ".+SubscribeTxStatus"
        - ".+SubscribeStatus"
        - ".+SubscribeNodeStatus"
        - ".+Describe"
        - ".+ServerReflectionInfo"

spans:
  collect:
    long-span-threshold: ${LONG_SPAN_THRESHOLD:1000}
    collect-only-errors: ${ONLY_ERROR_SPANS:true}